### PR TITLE
chore: added worker support

### PR DESCRIPTION
**Pull request by lquixada**
This work enables cross-fetch to work in workers environment such as Service Workers and Cloudflare Workers.

This PR addresses issues #69, #78 and #142.

### CODE REVIEW

**Comment by ThisIsMissEm** [comment]
Ah cool, in the meantime, Inrupt shipped their own fetch library which uses native feature if available: https://npm.im/@inrupt/universal-fetch

Which doesn't do polyfilling for browsers, given the wide support for fetch these days

**Comment by spencercap** [comment]
@lquixada 👏 THANK YOU !
in which version of cross-fetch is workers support live?

**Comment by lquixada** [comment]
@spencercap it'll be on version 4. you can test it using `npm install cross-fetch@latest-v4.x`. please let me know if you find any issues.

**Comment by spencercap** [comment]
@lquixada it works! thanks so much. 

the only thing i needed to change in this library's fork to get it working was to remove the `mode: "cors"` arg as you can see in the 2nd commit of this PR: https://github.com/algorand/js-algorand-sdk/pull/794 

it seems to me that the CF worker's `fetch` api doesn't support this even though it is supposed to by a direct mirror of the standard `fetch` api... which makes me wonder if it should be `cross-fetch`'s job to remove this arg IF in the workers env?

**Comment by lquixada** [comment]
@spencercap I'm glad that it worked out for you! Please note that `cross-fetch` purpose is to only act as proxy to different implementations depending on the environment. Eventual conflicts between implementations should be addressed by the libs (like `node-fetch` or `whatwg-fetch`), envs (like `node` or `service-worker`) or authors (like yourself).

**Pull request merged**
