### PR TITLE
chore: updated node-fetch to version 3.3.0

### PR DESCRIPTION
**Pull request by jeanpierrecarvalho**
### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)
- [x] :up: Upgrade dependencies

### 📚 Description

Updated node-fetch to the latest version 3.3.0.

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by rwlodarczyk-xealth** [comment]
#156 is the reference ticket for this PR.

**Comment by parithibang** [comment]
@jeanpierrecarvalho  The latest version is [3.3.1](https://github.com/node-fetch/node-fetch/releases/tag/v3.3.1) can this be updated.

**Comment by venkateshlb** [comment]
This PR will be so useful, Request to take a look at this PR and merge

**Comment by lquixada** [comment]
`node-fetch` from v3 is an ESM-only module and `cross-fetch` is CommonJS compatible. If there's a security issue, a patch should be requested on [node-fetch](https://github.com/node-fetch/node-fetch) `v2.x`. FWIW `cross-fetch@3.1.6` was released this morning with `node-fetch@2.6.11`.

**Pull request closed without merging**
